# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 6.0
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore NetCoreAwsCicd.Web/NetCoreAwsCicd.Web.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build NetCoreAwsCicd.Web/NetCoreAwsCicd.Web.csproj
      - echo Test started on `date`
      - dotnet test NetCoreAwsCicd.Web/NetCoreAwsCicd.Web.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./ NetCoreAwsCicd.Web/NetCoreAwsCicd.Web.csproj
      
artifacts:
  files:
    - ./**/*